[app]
title = WingPay OMEGA v8.0 STARK
package.name = wingpay_stark_sync
package.domain = com.inversioneswing.stark
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 8.0
requirements = python3,kivy,plyer,android,requests,certifi
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET, VIBRATE, WAKE_LOCK, RECEIVE_BOOT_COMPLETED, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE, POST_NOTIFICATIONS, FOREGROUND_SERVICE, CAMERA, READ_MEDIA_IMAGES, RECORD_AUDIO
android.api = 35
android.minapi = 21
android.sdk = 35
android.ndk = 25b
android.archs = arm64-v8a
android.allow_backup = True
